name: Tests

on:
  push:
    tags: ["v*"]
    branches: ["*"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      Github: true
    strategy:
      matrix:
        go:
          - "1.x"
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v ./...
