name: Tests

on:
  push:
    tags:
    branches:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      Github: true
    strategy:
      matrix:
        go:
          - '1.x'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: make build

    - name: Test
      run: make test
